### ISSUE TITLE
K-9 Mail security audit

### ISSUE THREAD

**Issue by shuvashish76** [MuntashirAkon/android-debloat-list#12]
https://blog.thunderbird.net/2023/07/k-9-mail-collaborates-with-ostif-and-7asecurity-security-audit/

Add `reason` for K-9 Mail (_suggestions_)

**Comment by MuntashirAkon** [comment]
Since **K-9 Mail** has received a formal audit, is there a reason for keeping FairEmail at all? Like VPN and password manager, we can make audit mandatory for these category of apps.

**Comment by shuvashish76** [comment]
Agreed 👍🏿
> _This project attempts to make it easy for a user to get started with a viable alternative._

**Comment by MuntashirAkon** [comment]
6b5c8bf7a6433ebfe69d5e4f6b781e6831d9d1b9
