### ISSUE TITLE
Add warning to `com.google.android.providers.media.module`

### ISSUE THREAD

**Issue by shuvashish76** [MuntashirAkon/android-debloat-list#30]
### Please check before submitting an issue

- [X] The bloatware in my proposal are present in the list
- [X] I have investigated the bloatware to confirm my concerns

### Source

Device: moto g71 5G
Android: 12

### Affected packages

- com.google.android.providers.media.module

### Reports

Media Storage `com.google.android.providers.media.module

https://github.com/MuntashirAkon/android-debloat-list/blob/f9cdddeb6770e10f735592ddf358bd89b0f86c94/pending.json#L264

1. Marked as unsafe but description says safe to remove...
2. The description is confusing, if it's only A11 affected or later versions also. Checked in my A12 device everything crashing if disabled & you can't access` /storage/emulated/0`. I'd suggest to remove. _~In Android 11 this is literally what~ provides access to files._
3. Move this package to `google.json`. Change `label` to Media Storage. Separate `web` link.

### Additional context

https://source.android.com/docs/core/media/media-provider

**Comment by MuntashirAkon** [comment]
`pending.json` hasn't been documented yet. I've only added a few labels so far.

**Comment by MuntashirAkon** [comment]
Fixed in 46ccc60ad8173c5d5b2d5fcfd006f64fd552fe55

**Comment by shuvashish76** [comment]
Add "warning" for unsafe package `com.android.externalstorage` & `com.android.providers.media` from aosp list.
