### ISSUE TITLE
(Suggestion app) Add Record You as an Audio recorder alternative

### ISSUE THREAD

**Issue by DodoLeDev** [MuntashirAkon/android-debloat-list#32]
Here is the issue created following [this comment](https://github.com/MuntashirAkon/android-debloat-list/pull/29#discussion_r1285195318), to track the progress of the Record You app integration in the suggestions list.
## Feature comparison between Audio Recorder (the current audio recorder alternative) and Record You

|Criterias|Audio Recorder|Record You| 
|--|--|--|
|Record audio| ✅ | ✅ |
|Record options | Naming pattern, audio format (m4a/wav/3gp), sample rate, bitrate, channel count | **Save folder location**, audio format (m4a/wav/3gp/**aac**/**opus**), sample rate, bitrate, channel count, **audio source**, naming pattern |
| App launcher shortcuts | ✅ | ✅ |
| Rename before saving | ✅ | ❌ |
| Recordings list | ✅ | ✅ |
| "Keep screen on while recording" feature | ✅ | ❌ |
|**Includes a screen recorder**| ❌ | ✅ |
| Screen record annotation tool | - | ✅ |
| Embedded audio stream to screen record | - | ✅ |
| **Theming** | Color palettes | Material You + light/dark |
| Waveform while recording | ✅ | ✅ |

**Comment by shuvashish76** [comment]
Comparison vs all known audio recorders #36

**Comment by MuntashirAkon** [comment]
Closed in favour of #36
