### ISSUE TITLE
Lenovo packages

### ISSUE THREAD

**Issue by shuvashish76** [MuntashirAkon/android-debloat-list#6]
This is an attempt to debloat Lenovo packages from my personal device. (originally requested [here](https://github.com/0x192/universal-android-debloater/issues/102))
Test device : Lenovo Tab4 8 plus (TB-8704X)
Currently UAD contains only 4 Lenovo packages : `com.lenovo.lsf.user`, `com.tblenovo.center`, `com.lenovo.ue.device`, `com.tblenovo.lenovotips`

**Comment by shuvashish76** [comment]
List of packages : ~`com.dti.lenovo.tablet`~ (#3), `com.kidoz.lenovo`, `com.lenovo.agent0`, `com.lenovo.csdkplatform`, `com.lenovo.dagent`, `com.lenovo.dsa`, `com.lenovo.launcher`, `com.lenovo.launcher.provider`, `com.lenovo.lsf`, `com.lenovo.lsf.device`, `com.lenovo.ocpl`, `com.lenovo.ota`, `com.lenovo.tab4_8plus`, `com.lenovo.ue.device`, `com.lenovo.wallpaper`, `com.lenovo.weather.theme.dreamlandPad`, `com.tblenovo.lewea`, `com.tblenovo.setup`, `com.tblenovo.soundrecorder`, `com.tblenovo.whatsnewclient`, `com.tblenovo.whatsnewhost`

Note to self:
 - [ ] add package `description` where possible
 - [ ] `web` search & add investigation reports if possible (add pithus [dot] org report when required)
 - [ ] test on your device
 - [ ] instead of spamming with multiple commits try to add with minimum commits then open PR

**Comment by MuntashirAkon** [comment]
You can use PR #3 to add all the listed apps when you're finished with your investigation.
