### ISSUE TITLE
Add labels to the missing items and make it mandatory

### ISSUE THREAD

**Issue by MuntashirAkon** [MuntashirAkon/android-debloat-list#8]
| type | # of missing labels
| --- | ---
| aosp | 0
| carrier | 0
| google | 0
| misc | 242
| oem | 1390
| pending | 240

[missing-labels.txt](https://github.com/MuntashirAkon/android-debloat-list/files/12051820/missing-labels.txt)

**Comment by Application-maker** [comment]
My PR #11 partially fixes that
